# Generated by Django 4.2.2 on 2023-06-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_rename_post_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
